import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { colors } from '../../theme/colors';

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const ReportDetailScreen = ({ route, navigation }) => {
    const { reportData } = route.params || {
        reportData: { id: 1, name: 'Demo Project', zone: 'Zone V', status: 'High Risk', color: '#EF4444' }
    };

    // Helper to get dynamic content based on risk status
    const getRiskDetails = (status) => {
        switch (status) {
            case 'Critical':
                return {
                    rec: 'Immediate Retrofitting Required',
                    analysis: 'Non-ductile reinforcement detected. Structure is highly vulnerable to shear failure. Immediate evacuation and strengthening recommended.'
                };
            case 'High Risk':
                return {
                    rec: 'Install Shear Walls',
                    analysis: 'Significant torsional irregularity observed. Building drift exceeds safe limits for Zone IV. Retrofitting with shear walls is advised.'
                };
            case 'Medium Risk':
                return {
                    rec: 'Strengthen Column Joints',
                    analysis: 'Minor cracking in beam-column joints. Structure meets baseline safety but requires strengthening to prevent long-term seismic damage.'
                };
            case 'Low Risk':
                return {
                    rec: 'Routine Maintenance',
                    analysis: 'Structure complies with IS 1893 standards. No major defects found. Regular inspection recommended every 2 years.'
                };
            default:
                return {
                    rec: 'Structural Audit Pending',
                    analysis: 'Preliminary visual inspection completed. Detailed structural audit is required to determine exact seismic vulnerability.'
                };
        }
    };

    const details = getRiskDetails(reportData.status);

    const generatePDF = async () => {
        const html = `
            <html>
                <body style="font-family: Helvetica, Arial, sans-serif; padding: 40px;">
                    <h1 style="color: #333;">Seismic Safety Report: ${reportData.name}</h1>
                    <p style="color: #666;">Generated on ${new Date().toLocaleDateString()}</p>
                    <hr style="border: 1px solid #eee; margin: 20px 0;" />
                    
                    <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px;">
                        <h2 style="color: #111; margin-top: 0;">Summary</h2>
                        <p><strong>Risk Level:</strong> <span style="color: ${reportData.color}; font-weight: bold;">${reportData.status}</span></p>
                        <p><strong>Zone:</strong> ${reportData.zone}</p>
                        <p><strong>Recommendation:</strong> ${details.rec}</p>
                    </div>

                    <div style="margin-top: 30px;">
                        <h3>Structural Analysis</h3>
                        <p>The building structure (${reportData.name}) located in ${reportData.zone} has been analyzed.</p>
                        <p>${details.analysis}</p>
                        <p style="margin-top: 10px;">Soil conditions were factored into this assessment.</p>
                    </div>

                    <footer style="margin-top: 50px; text-align: center; color: #999; font-size: 12px;">
                        Generated by StructIQ App
                    </footer>
                </body>
            </html>
        `;


        try {
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (error) {
            console.error('Error generating PDF:', error);
            alert('Failed to generate PDF');
        }
    };


    const handleDelete = () => {
        // Navigate back and pass the ID to delete
        navigation.navigate('EngineerDashboard', { deletedReportId: reportData.id });
    };

    return (
        <View style={styles.container}>
            <View style={styles.header}>
                <TouchableOpacity onPress={() => navigation.goBack()}>
                    <Text style={styles.backText}>← Back</Text>
                </TouchableOpacity>
                <Text style={styles.title}>{reportData.name}</Text>

                <TouchableOpacity onPress={handleDelete} style={styles.deleteBtn}>
                    <Text style={styles.deleteIcon}>🗑️</Text>
                </TouchableOpacity>
            </View>

            <View style={styles.pdfPlaceholder}>
                <Text style={styles.pdfIcon}>📄</Text>
                <Text style={styles.pdfText}>{reportData.name} Report.pdf</Text>
                <Text style={styles.pdfSub}>Generated on {new Date().toLocaleDateString()}</Text>

                <View style={styles.divider} />

                <Text style={styles.sectionHeader}>Summary</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Risk Level</Text>
                    <Text style={[styles.val, { color: reportData.color }]}>{reportData.status.toUpperCase()}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Zone</Text>
                    <Text style={styles.val}>{reportData.zone}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Recommendation</Text>
                    <Text style={[styles.val, { flex: 1, textAlign: 'right' }]}>{details.rec}</Text>
                </View>
            </View>

            <TouchableOpacity style={styles.downloadBtn} onPress={generatePDF}>
                <Text style={styles.downloadText}>DOWNLOAD PDF</Text>
            </TouchableOpacity>
        </View>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background, padding: 20 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 30 },
    backText: { color: colors.textSecondary },
    title: { color: colors.text, fontSize: 20, fontWeight: 'bold', flex: 1, textAlign: 'center' },
    deleteBtn: { padding: 5 },
    deleteIcon: { fontSize: 20 },

    pdfPlaceholder: {
        flex: 1,
        backgroundColor: 'white',
        borderRadius: 8,
        padding: 30,
        alignItems: 'center'
    },
    pdfIcon: { fontSize: 60, marginBottom: 10, color: '#333' },
    pdfText: { color: '#333', fontSize: 18, fontWeight: 'bold' },
    pdfSub: { color: '#666', fontSize: 12, marginBottom: 30 },

    divider: { height: 1, backgroundColor: '#eee', width: '100%', marginBottom: 30 },

    sectionHeader: { alignSelf: 'flex-start', color: '#333', fontWeight: 'bold', marginBottom: 15 },
    row: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: 10 },
    label: { color: '#666' },
    val: { color: '#333', fontWeight: 'bold' },
    valHigh: { color: '#EF4444', fontWeight: 'bold' },

    downloadBtn: {
        backgroundColor: colors.primary,
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20
    },
    downloadText: { color: 'white', fontWeight: 'bold', letterSpacing: 1 }
});

export default ReportDetailScreen;
